### PR TITLE
Updated implementation for firmware Version 01.02.037.03.12.EURO.SIP 

### PR DESCRIPTION
**Pull request by comentator**

### CODE REVIEW

**Comment by comentator** [comment]
The firmware is one that is deployed on the devices shipped by Vodafone/Unitymedia in Germany

**Comment by f-s** [comment]
Thanks!!! This solved most of my problems. Any Idea how to add an IPv6 Port Filter I am missng this option in this firmware.

**Comment by diveflo** [comment]
Awesome - thanks!
I'll give it a whirl on my modem, which is still on the old firmware, and merge it asap:)

**Comment by diveflo** [comment]
> The firmware is one that is deployed on the devices shipped by Vodafone/Unitymedia in Germany

Is it? Mine is from Vodafone Germany as well, but I'm still on `AR01.01.117.01_091718_70.PC20.10`
Unfortunately, your changes break the tool for the old firmware.
I'll merge your changes to a dev branch and then try to support both versions - maybe you'd like to help there? I'd update in here once the new branch is there.

**Comment by diveflo** [comment]
@comentator I'll merge this in and commit my fix to support both versions after that. I'd be great if you could test it afterwards, as I don't have a modem with the newer firmware at hand.
Thanks!

**Comment by comentator** [comment]
@diveflo Sorry, wasn't online for the weekend. I will test it tonight and report back here.

**Comment by comentator** [comment]
For me it does work

**Pull request merged**
